/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizesRouteImport } from './routes/quizes'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as MyhorsesRouteImport } from './routes/myhorses'
import { Route as MyalpacasRouteImport } from './routes/myalpacas'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HorsesRouteImport } from './routes/horses'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as CleanstableRouteImport } from './routes/cleanstable'
import { Route as BuyhorsesRouteImport } from './routes/buyhorses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletWalletIdRouteImport } from './routes/wallet.$walletId'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as CompetitionCreateRouteImport } from './routes/competition.create'
import { Route as CompetitionCompeteRouteImport } from './routes/competition.compete'
import { Route as AdAdIdRouteImport } from './routes/ad.$adId'
import { Route as AnimalAnimalIdRouteImport } from './routes/$animal.$animalId'
import { Route as QuizQuizIdUpdateRouteImport } from './routes/quiz.$quizId.update'
import { Route as HorseHorseIdBreedRouteImport } from './routes/horse.$horseId.breed'
import { Route as AnimalAnimalIdUpdateRouteImport } from './routes/$animal.$animalId.update'
import { Route as AnimalAnimalIdInfoRouteImport } from './routes/$animal.$animalId.info'
import { Route as AnimalAnimalIdDeleteRouteImport } from './routes/$animal.$animalId.delete'

const QuizesRoute = QuizesRouteImport.update({
  id: '/quizes',
  path: '/quizes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const MyhorsesRoute = MyhorsesRouteImport.update({
  id: '/myhorses',
  path: '/myhorses',
  getParentRoute: () => rootRouteImport,
} as any)
const MyalpacasRoute = MyalpacasRouteImport.update({
  id: '/myalpacas',
  path: '/myalpacas',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesRoute = HorsesRouteImport.update({
  id: '/horses',
  path: '/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanstableRoute = CleanstableRouteImport.update({
  id: '/cleanstable',
  path: '/cleanstable',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyhorsesRoute = BuyhorsesRouteImport.update({
  id: '/buyhorses',
  path: '/buyhorses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletWalletIdRoute = WalletWalletIdRouteImport.update({
  id: '/wallet/$walletId',
  path: '/wallet/$walletId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => QuizRoute,
} as any)
const CompetitionCreateRoute = CompetitionCreateRouteImport.update({
  id: '/competition/create',
  path: '/competition/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionCompeteRoute = CompetitionCompeteRouteImport.update({
  id: '/competition/compete',
  path: '/competition/compete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdAdIdRoute = AdAdIdRouteImport.update({
  id: '/ad/$adId',
  path: '/ad/$adId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalAnimalIdRoute = AnimalAnimalIdRouteImport.update({
  id: '/$animal/$animalId',
  path: '/$animal/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdUpdateRoute = QuizQuizIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => QuizQuizIdRoute,
} as any)
const HorseHorseIdBreedRoute = HorseHorseIdBreedRouteImport.update({
  id: '/horse/$horseId/breed',
  path: '/horse/$horseId/breed',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalAnimalIdUpdateRoute = AnimalAnimalIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => AnimalAnimalIdRoute,
} as any)
const AnimalAnimalIdInfoRoute = AnimalAnimalIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AnimalAnimalIdRoute,
} as any)
const AnimalAnimalIdDeleteRoute = AnimalAnimalIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => AnimalAnimalIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyhorses': typeof BuyhorsesRoute
  '/cleanstable': typeof CleanstableRoute
  '/competitions': typeof CompetitionsRoute
  '/horses': typeof HorsesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/myalpacas': typeof MyalpacasRoute
  '/myhorses': typeof MyhorsesRoute
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quizes': typeof QuizesRoute
  '/$animal/$animalId': typeof AnimalAnimalIdRouteWithChildren
  '/ad/$adId': typeof AdAdIdRoute
  '/competition/compete': typeof CompetitionCompeteRoute
  '/competition/create': typeof CompetitionCreateRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/wallet/$walletId': typeof WalletWalletIdRoute
  '/$animal/$animalId/delete': typeof AnimalAnimalIdDeleteRoute
  '/$animal/$animalId/info': typeof AnimalAnimalIdInfoRoute
  '/$animal/$animalId/update': typeof AnimalAnimalIdUpdateRoute
  '/horse/$horseId/breed': typeof HorseHorseIdBreedRoute
  '/quiz/$quizId/update': typeof QuizQuizIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyhorses': typeof BuyhorsesRoute
  '/cleanstable': typeof CleanstableRoute
  '/competitions': typeof CompetitionsRoute
  '/horses': typeof HorsesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/myalpacas': typeof MyalpacasRoute
  '/myhorses': typeof MyhorsesRoute
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quizes': typeof QuizesRoute
  '/$animal/$animalId': typeof AnimalAnimalIdRouteWithChildren
  '/ad/$adId': typeof AdAdIdRoute
  '/competition/compete': typeof CompetitionCompeteRoute
  '/competition/create': typeof CompetitionCreateRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/wallet/$walletId': typeof WalletWalletIdRoute
  '/$animal/$animalId/delete': typeof AnimalAnimalIdDeleteRoute
  '/$animal/$animalId/info': typeof AnimalAnimalIdInfoRoute
  '/$animal/$animalId/update': typeof AnimalAnimalIdUpdateRoute
  '/horse/$horseId/breed': typeof HorseHorseIdBreedRoute
  '/quiz/$quizId/update': typeof QuizQuizIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyhorses': typeof BuyhorsesRoute
  '/cleanstable': typeof CleanstableRoute
  '/competitions': typeof CompetitionsRoute
  '/horses': typeof HorsesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/myalpacas': typeof MyalpacasRoute
  '/myhorses': typeof MyhorsesRoute
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quizes': typeof QuizesRoute
  '/$animal/$animalId': typeof AnimalAnimalIdRouteWithChildren
  '/ad/$adId': typeof AdAdIdRoute
  '/competition/compete': typeof CompetitionCompeteRoute
  '/competition/create': typeof CompetitionCreateRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/wallet/$walletId': typeof WalletWalletIdRoute
  '/$animal/$animalId/delete': typeof AnimalAnimalIdDeleteRoute
  '/$animal/$animalId/info': typeof AnimalAnimalIdInfoRoute
  '/$animal/$animalId/update': typeof AnimalAnimalIdUpdateRoute
  '/horse/$horseId/breed': typeof HorseHorseIdBreedRoute
  '/quiz/$quizId/update': typeof QuizQuizIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyhorses'
    | '/cleanstable'
    | '/competitions'
    | '/horses'
    | '/leaderboard'
    | '/myalpacas'
    | '/myhorses'
    | '/puzzles'
    | '/quiz'
    | '/quizes'
    | '/$animal/$animalId'
    | '/ad/$adId'
    | '/competition/compete'
    | '/competition/create'
    | '/quiz/$quizId'
    | '/wallet/$walletId'
    | '/$animal/$animalId/delete'
    | '/$animal/$animalId/info'
    | '/$animal/$animalId/update'
    | '/horse/$horseId/breed'
    | '/quiz/$quizId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyhorses'
    | '/cleanstable'
    | '/competitions'
    | '/horses'
    | '/leaderboard'
    | '/myalpacas'
    | '/myhorses'
    | '/puzzles'
    | '/quiz'
    | '/quizes'
    | '/$animal/$animalId'
    | '/ad/$adId'
    | '/competition/compete'
    | '/competition/create'
    | '/quiz/$quizId'
    | '/wallet/$walletId'
    | '/$animal/$animalId/delete'
    | '/$animal/$animalId/info'
    | '/$animal/$animalId/update'
    | '/horse/$horseId/breed'
    | '/quiz/$quizId/update'
  id:
    | '__root__'
    | '/'
    | '/buyhorses'
    | '/cleanstable'
    | '/competitions'
    | '/horses'
    | '/leaderboard'
    | '/myalpacas'
    | '/myhorses'
    | '/puzzles'
    | '/quiz'
    | '/quizes'
    | '/$animal/$animalId'
    | '/ad/$adId'
    | '/competition/compete'
    | '/competition/create'
    | '/quiz/$quizId'
    | '/wallet/$walletId'
    | '/$animal/$animalId/delete'
    | '/$animal/$animalId/info'
    | '/$animal/$animalId/update'
    | '/horse/$horseId/breed'
    | '/quiz/$quizId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyhorsesRoute: typeof BuyhorsesRoute
  CleanstableRoute: typeof CleanstableRoute
  CompetitionsRoute: typeof CompetitionsRoute
  HorsesRoute: typeof HorsesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyalpacasRoute: typeof MyalpacasRoute
  MyhorsesRoute: typeof MyhorsesRoute
  PuzzlesRoute: typeof PuzzlesRoute
  QuizRoute: typeof QuizRouteWithChildren
  QuizesRoute: typeof QuizesRoute
  AnimalAnimalIdRoute: typeof AnimalAnimalIdRouteWithChildren
  AdAdIdRoute: typeof AdAdIdRoute
  CompetitionCompeteRoute: typeof CompetitionCompeteRoute
  CompetitionCreateRoute: typeof CompetitionCreateRoute
  WalletWalletIdRoute: typeof WalletWalletIdRoute
  HorseHorseIdBreedRoute: typeof HorseHorseIdBreedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quizes': {
      id: '/quizes'
      path: '/quizes'
      fullPath: '/quizes'
      preLoaderRoute: typeof QuizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myhorses': {
      id: '/myhorses'
      path: '/myhorses'
      fullPath: '/myhorses'
      preLoaderRoute: typeof MyhorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myalpacas': {
      id: '/myalpacas'
      path: '/myalpacas'
      fullPath: '/myalpacas'
      preLoaderRoute: typeof MyalpacasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses': {
      id: '/horses'
      path: '/horses'
      fullPath: '/horses'
      preLoaderRoute: typeof HorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanstable': {
      id: '/cleanstable'
      path: '/cleanstable'
      fullPath: '/cleanstable'
      preLoaderRoute: typeof CleanstableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyhorses': {
      id: '/buyhorses'
      path: '/buyhorses'
      fullPath: '/buyhorses'
      preLoaderRoute: typeof BuyhorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$walletId': {
      id: '/wallet/$walletId'
      path: '/wallet/$walletId'
      fullPath: '/wallet/$walletId'
      preLoaderRoute: typeof WalletWalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/competition/create': {
      id: '/competition/create'
      path: '/competition/create'
      fullPath: '/competition/create'
      preLoaderRoute: typeof CompetitionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition/compete': {
      id: '/competition/compete'
      path: '/competition/compete'
      fullPath: '/competition/compete'
      preLoaderRoute: typeof CompetitionCompeteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad/$adId': {
      id: '/ad/$adId'
      path: '/ad/$adId'
      fullPath: '/ad/$adId'
      preLoaderRoute: typeof AdAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$animal/$animalId': {
      id: '/$animal/$animalId'
      path: '/$animal/$animalId'
      fullPath: '/$animal/$animalId'
      preLoaderRoute: typeof AnimalAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/update': {
      id: '/quiz/$quizId/update'
      path: '/update'
      fullPath: '/quiz/$quizId/update'
      preLoaderRoute: typeof QuizQuizIdUpdateRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
    '/horse/$horseId/breed': {
      id: '/horse/$horseId/breed'
      path: '/horse/$horseId/breed'
      fullPath: '/horse/$horseId/breed'
      preLoaderRoute: typeof HorseHorseIdBreedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$animal/$animalId/update': {
      id: '/$animal/$animalId/update'
      path: '/update'
      fullPath: '/$animal/$animalId/update'
      preLoaderRoute: typeof AnimalAnimalIdUpdateRouteImport
      parentRoute: typeof AnimalAnimalIdRoute
    }
    '/$animal/$animalId/info': {
      id: '/$animal/$animalId/info'
      path: '/info'
      fullPath: '/$animal/$animalId/info'
      preLoaderRoute: typeof AnimalAnimalIdInfoRouteImport
      parentRoute: typeof AnimalAnimalIdRoute
    }
    '/$animal/$animalId/delete': {
      id: '/$animal/$animalId/delete'
      path: '/delete'
      fullPath: '/$animal/$animalId/delete'
      preLoaderRoute: typeof AnimalAnimalIdDeleteRouteImport
      parentRoute: typeof AnimalAnimalIdRoute
    }
  }
}

interface QuizQuizIdRouteChildren {
  QuizQuizIdUpdateRoute: typeof QuizQuizIdUpdateRoute
}

const QuizQuizIdRouteChildren: QuizQuizIdRouteChildren = {
  QuizQuizIdUpdateRoute: QuizQuizIdUpdateRoute,
}

const QuizQuizIdRouteWithChildren = QuizQuizIdRoute._addFileChildren(
  QuizQuizIdRouteChildren,
)

interface QuizRouteChildren {
  QuizQuizIdRoute: typeof QuizQuizIdRouteWithChildren
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizQuizIdRoute: QuizQuizIdRouteWithChildren,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

interface AnimalAnimalIdRouteChildren {
  AnimalAnimalIdDeleteRoute: typeof AnimalAnimalIdDeleteRoute
  AnimalAnimalIdInfoRoute: typeof AnimalAnimalIdInfoRoute
  AnimalAnimalIdUpdateRoute: typeof AnimalAnimalIdUpdateRoute
}

const AnimalAnimalIdRouteChildren: AnimalAnimalIdRouteChildren = {
  AnimalAnimalIdDeleteRoute: AnimalAnimalIdDeleteRoute,
  AnimalAnimalIdInfoRoute: AnimalAnimalIdInfoRoute,
  AnimalAnimalIdUpdateRoute: AnimalAnimalIdUpdateRoute,
}

const AnimalAnimalIdRouteWithChildren = AnimalAnimalIdRoute._addFileChildren(
  AnimalAnimalIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyhorsesRoute: BuyhorsesRoute,
  CleanstableRoute: CleanstableRoute,
  CompetitionsRoute: CompetitionsRoute,
  HorsesRoute: HorsesRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyalpacasRoute: MyalpacasRoute,
  MyhorsesRoute: MyhorsesRoute,
  PuzzlesRoute: PuzzlesRoute,
  QuizRoute: QuizRouteWithChildren,
  QuizesRoute: QuizesRoute,
  AnimalAnimalIdRoute: AnimalAnimalIdRouteWithChildren,
  AdAdIdRoute: AdAdIdRoute,
  CompetitionCompeteRoute: CompetitionCompeteRoute,
  CompetitionCreateRoute: CompetitionCreateRoute,
  WalletWalletIdRoute: WalletWalletIdRoute,
  HorseHorseIdBreedRoute: HorseHorseIdBreedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
