/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as QuizesRouteImport } from './routes/quizes'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as MyhorsesRouteImport } from './routes/myhorses'
import { Route as MyalpacasRouteImport } from './routes/myalpacas'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as HorsesRouteImport } from './routes/horses'
import { Route as HorseCreateRouteImport } from './routes/horse-create'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as CleanstableRouteImport } from './routes/cleanstable'
import { Route as BuyhorsesRouteImport } from './routes/buyhorses'
import { Route as BreedRouteImport } from './routes/breed'
import { Route as AlpacasRouteImport } from './routes/alpacas'
import { Route as AlpacaCreateRouteImport } from './routes/alpaca-create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as MyhorsesAllRouteImport } from './routes/myhorses.all'
import { Route as MyhorsesFilterRouteImport } from './routes/myhorses.$filter'
import { Route as CompetitionCreateRouteImport } from './routes/competition.create'
import { Route as AdAdIdRouteImport } from './routes/ad.$adId'
import { Route as AnimalAnimalIdRouteImport } from './routes/$animal.$animalId'
import { Route as QuizQuizIdUpdateRouteImport } from './routes/quiz.$quizId.update'
import { Route as CompetitionCompIdUpdateRouteImport } from './routes/competition.$compId.update'
import { Route as CompetitionCompIdCompeteRouteImport } from './routes/competition.$compId.compete'
import { Route as AnimalAnimalIdUpdateRouteImport } from './routes/$animal.$animalId.update'
import { Route as AnimalAnimalIdResultsRouteImport } from './routes/$animal.$animalId.results'
import { Route as AnimalAnimalIdInfoRouteImport } from './routes/$animal.$animalId.info'
import { Route as AnimalAnimalIdFoalsRouteImport } from './routes/$animal.$animalId.foals'
import { Route as AnimalAnimalIdDeleteRouteImport } from './routes/$animal.$animalId.delete'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizesRoute = QuizesRouteImport.update({
  id: '/quizes',
  path: '/quizes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const MyhorsesRoute = MyhorsesRouteImport.update({
  id: '/myhorses',
  path: '/myhorses',
  getParentRoute: () => rootRouteImport,
} as any)
const MyalpacasRoute = MyalpacasRouteImport.update({
  id: '/myalpacas',
  path: '/myalpacas',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesRoute = HorsesRouteImport.update({
  id: '/horses',
  path: '/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const HorseCreateRoute = HorseCreateRouteImport.update({
  id: '/horse-create',
  path: '/horse-create',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanstableRoute = CleanstableRouteImport.update({
  id: '/cleanstable',
  path: '/cleanstable',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyhorsesRoute = BuyhorsesRouteImport.update({
  id: '/buyhorses',
  path: '/buyhorses',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedRoute = BreedRouteImport.update({
  id: '/breed',
  path: '/breed',
  getParentRoute: () => rootRouteImport,
} as any)
const AlpacasRoute = AlpacasRouteImport.update({
  id: '/alpacas',
  path: '/alpacas',
  getParentRoute: () => rootRouteImport,
} as any)
const AlpacaCreateRoute = AlpacaCreateRouteImport.update({
  id: '/alpaca-create',
  path: '/alpaca-create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => QuizRoute,
} as any)
const MyhorsesAllRoute = MyhorsesAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => MyhorsesRoute,
} as any)
const MyhorsesFilterRoute = MyhorsesFilterRouteImport.update({
  id: '/$filter',
  path: '/$filter',
  getParentRoute: () => MyhorsesRoute,
} as any)
const CompetitionCreateRoute = CompetitionCreateRouteImport.update({
  id: '/competition/create',
  path: '/competition/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdAdIdRoute = AdAdIdRouteImport.update({
  id: '/ad/$adId',
  path: '/ad/$adId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalAnimalIdRoute = AnimalAnimalIdRouteImport.update({
  id: '/$animal/$animalId',
  path: '/$animal/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdUpdateRoute = QuizQuizIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => QuizQuizIdRoute,
} as any)
const CompetitionCompIdUpdateRoute = CompetitionCompIdUpdateRouteImport.update({
  id: '/competition/$compId/update',
  path: '/competition/$compId/update',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionCompIdCompeteRoute =
  CompetitionCompIdCompeteRouteImport.update({
    id: '/competition/$compId/compete',
    path: '/competition/$compId/compete',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimalAnimalIdUpdateRoute = AnimalAnimalIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => AnimalAnimalIdRoute,
} as any)
const AnimalAnimalIdResultsRoute = AnimalAnimalIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AnimalAnimalIdRoute,
} as any)
const AnimalAnimalIdInfoRoute = AnimalAnimalIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AnimalAnimalIdRoute,
} as any)
const AnimalAnimalIdFoalsRoute = AnimalAnimalIdFoalsRouteImport.update({
  id: '/foals',
  path: '/foals',
  getParentRoute: () => AnimalAnimalIdRoute,
} as any)
const AnimalAnimalIdDeleteRoute = AnimalAnimalIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => AnimalAnimalIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alpaca-create': typeof AlpacaCreateRoute
  '/alpacas': typeof AlpacasRoute
  '/breed': typeof BreedRoute
  '/buyhorses': typeof BuyhorsesRoute
  '/cleanstable': typeof CleanstableRoute
  '/competitions': typeof CompetitionsRoute
  '/horse-create': typeof HorseCreateRoute
  '/horses': typeof HorsesRoute
  '/images': typeof ImagesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/myalpacas': typeof MyalpacasRoute
  '/myhorses': typeof MyhorsesRouteWithChildren
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quizes': typeof QuizesRoute
  '/wallet': typeof WalletRoute
  '/$animal/$animalId': typeof AnimalAnimalIdRouteWithChildren
  '/ad/$adId': typeof AdAdIdRoute
  '/competition/create': typeof CompetitionCreateRoute
  '/myhorses/$filter': typeof MyhorsesFilterRoute
  '/myhorses/all': typeof MyhorsesAllRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/$animal/$animalId/delete': typeof AnimalAnimalIdDeleteRoute
  '/$animal/$animalId/foals': typeof AnimalAnimalIdFoalsRoute
  '/$animal/$animalId/info': typeof AnimalAnimalIdInfoRoute
  '/$animal/$animalId/results': typeof AnimalAnimalIdResultsRoute
  '/$animal/$animalId/update': typeof AnimalAnimalIdUpdateRoute
  '/competition/$compId/compete': typeof CompetitionCompIdCompeteRoute
  '/competition/$compId/update': typeof CompetitionCompIdUpdateRoute
  '/quiz/$quizId/update': typeof QuizQuizIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alpaca-create': typeof AlpacaCreateRoute
  '/alpacas': typeof AlpacasRoute
  '/breed': typeof BreedRoute
  '/buyhorses': typeof BuyhorsesRoute
  '/cleanstable': typeof CleanstableRoute
  '/competitions': typeof CompetitionsRoute
  '/horse-create': typeof HorseCreateRoute
  '/horses': typeof HorsesRoute
  '/images': typeof ImagesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/myalpacas': typeof MyalpacasRoute
  '/myhorses': typeof MyhorsesRouteWithChildren
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quizes': typeof QuizesRoute
  '/wallet': typeof WalletRoute
  '/$animal/$animalId': typeof AnimalAnimalIdRouteWithChildren
  '/ad/$adId': typeof AdAdIdRoute
  '/competition/create': typeof CompetitionCreateRoute
  '/myhorses/$filter': typeof MyhorsesFilterRoute
  '/myhorses/all': typeof MyhorsesAllRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/$animal/$animalId/delete': typeof AnimalAnimalIdDeleteRoute
  '/$animal/$animalId/foals': typeof AnimalAnimalIdFoalsRoute
  '/$animal/$animalId/info': typeof AnimalAnimalIdInfoRoute
  '/$animal/$animalId/results': typeof AnimalAnimalIdResultsRoute
  '/$animal/$animalId/update': typeof AnimalAnimalIdUpdateRoute
  '/competition/$compId/compete': typeof CompetitionCompIdCompeteRoute
  '/competition/$compId/update': typeof CompetitionCompIdUpdateRoute
  '/quiz/$quizId/update': typeof QuizQuizIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alpaca-create': typeof AlpacaCreateRoute
  '/alpacas': typeof AlpacasRoute
  '/breed': typeof BreedRoute
  '/buyhorses': typeof BuyhorsesRoute
  '/cleanstable': typeof CleanstableRoute
  '/competitions': typeof CompetitionsRoute
  '/horse-create': typeof HorseCreateRoute
  '/horses': typeof HorsesRoute
  '/images': typeof ImagesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/myalpacas': typeof MyalpacasRoute
  '/myhorses': typeof MyhorsesRouteWithChildren
  '/puzzles': typeof PuzzlesRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quizes': typeof QuizesRoute
  '/wallet': typeof WalletRoute
  '/$animal/$animalId': typeof AnimalAnimalIdRouteWithChildren
  '/ad/$adId': typeof AdAdIdRoute
  '/competition/create': typeof CompetitionCreateRoute
  '/myhorses/$filter': typeof MyhorsesFilterRoute
  '/myhorses/all': typeof MyhorsesAllRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/$animal/$animalId/delete': typeof AnimalAnimalIdDeleteRoute
  '/$animal/$animalId/foals': typeof AnimalAnimalIdFoalsRoute
  '/$animal/$animalId/info': typeof AnimalAnimalIdInfoRoute
  '/$animal/$animalId/results': typeof AnimalAnimalIdResultsRoute
  '/$animal/$animalId/update': typeof AnimalAnimalIdUpdateRoute
  '/competition/$compId/compete': typeof CompetitionCompIdCompeteRoute
  '/competition/$compId/update': typeof CompetitionCompIdUpdateRoute
  '/quiz/$quizId/update': typeof QuizQuizIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alpaca-create'
    | '/alpacas'
    | '/breed'
    | '/buyhorses'
    | '/cleanstable'
    | '/competitions'
    | '/horse-create'
    | '/horses'
    | '/images'
    | '/leaderboard'
    | '/myalpacas'
    | '/myhorses'
    | '/puzzles'
    | '/quiz'
    | '/quizes'
    | '/wallet'
    | '/$animal/$animalId'
    | '/ad/$adId'
    | '/competition/create'
    | '/myhorses/$filter'
    | '/myhorses/all'
    | '/quiz/$quizId'
    | '/$animal/$animalId/delete'
    | '/$animal/$animalId/foals'
    | '/$animal/$animalId/info'
    | '/$animal/$animalId/results'
    | '/$animal/$animalId/update'
    | '/competition/$compId/compete'
    | '/competition/$compId/update'
    | '/quiz/$quizId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alpaca-create'
    | '/alpacas'
    | '/breed'
    | '/buyhorses'
    | '/cleanstable'
    | '/competitions'
    | '/horse-create'
    | '/horses'
    | '/images'
    | '/leaderboard'
    | '/myalpacas'
    | '/myhorses'
    | '/puzzles'
    | '/quiz'
    | '/quizes'
    | '/wallet'
    | '/$animal/$animalId'
    | '/ad/$adId'
    | '/competition/create'
    | '/myhorses/$filter'
    | '/myhorses/all'
    | '/quiz/$quizId'
    | '/$animal/$animalId/delete'
    | '/$animal/$animalId/foals'
    | '/$animal/$animalId/info'
    | '/$animal/$animalId/results'
    | '/$animal/$animalId/update'
    | '/competition/$compId/compete'
    | '/competition/$compId/update'
    | '/quiz/$quizId/update'
  id:
    | '__root__'
    | '/'
    | '/alpaca-create'
    | '/alpacas'
    | '/breed'
    | '/buyhorses'
    | '/cleanstable'
    | '/competitions'
    | '/horse-create'
    | '/horses'
    | '/images'
    | '/leaderboard'
    | '/myalpacas'
    | '/myhorses'
    | '/puzzles'
    | '/quiz'
    | '/quizes'
    | '/wallet'
    | '/$animal/$animalId'
    | '/ad/$adId'
    | '/competition/create'
    | '/myhorses/$filter'
    | '/myhorses/all'
    | '/quiz/$quizId'
    | '/$animal/$animalId/delete'
    | '/$animal/$animalId/foals'
    | '/$animal/$animalId/info'
    | '/$animal/$animalId/results'
    | '/$animal/$animalId/update'
    | '/competition/$compId/compete'
    | '/competition/$compId/update'
    | '/quiz/$quizId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlpacaCreateRoute: typeof AlpacaCreateRoute
  AlpacasRoute: typeof AlpacasRoute
  BreedRoute: typeof BreedRoute
  BuyhorsesRoute: typeof BuyhorsesRoute
  CleanstableRoute: typeof CleanstableRoute
  CompetitionsRoute: typeof CompetitionsRoute
  HorseCreateRoute: typeof HorseCreateRoute
  HorsesRoute: typeof HorsesRoute
  ImagesRoute: typeof ImagesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyalpacasRoute: typeof MyalpacasRoute
  MyhorsesRoute: typeof MyhorsesRouteWithChildren
  PuzzlesRoute: typeof PuzzlesRoute
  QuizRoute: typeof QuizRouteWithChildren
  QuizesRoute: typeof QuizesRoute
  WalletRoute: typeof WalletRoute
  AnimalAnimalIdRoute: typeof AnimalAnimalIdRouteWithChildren
  AdAdIdRoute: typeof AdAdIdRoute
  CompetitionCreateRoute: typeof CompetitionCreateRoute
  CompetitionCompIdCompeteRoute: typeof CompetitionCompIdCompeteRoute
  CompetitionCompIdUpdateRoute: typeof CompetitionCompIdUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizes': {
      id: '/quizes'
      path: '/quizes'
      fullPath: '/quizes'
      preLoaderRoute: typeof QuizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myhorses': {
      id: '/myhorses'
      path: '/myhorses'
      fullPath: '/myhorses'
      preLoaderRoute: typeof MyhorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myalpacas': {
      id: '/myalpacas'
      path: '/myalpacas'
      fullPath: '/myalpacas'
      preLoaderRoute: typeof MyalpacasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses': {
      id: '/horses'
      path: '/horses'
      fullPath: '/horses'
      preLoaderRoute: typeof HorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horse-create': {
      id: '/horse-create'
      path: '/horse-create'
      fullPath: '/horse-create'
      preLoaderRoute: typeof HorseCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanstable': {
      id: '/cleanstable'
      path: '/cleanstable'
      fullPath: '/cleanstable'
      preLoaderRoute: typeof CleanstableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyhorses': {
      id: '/buyhorses'
      path: '/buyhorses'
      fullPath: '/buyhorses'
      preLoaderRoute: typeof BuyhorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breed': {
      id: '/breed'
      path: '/breed'
      fullPath: '/breed'
      preLoaderRoute: typeof BreedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpacas': {
      id: '/alpacas'
      path: '/alpacas'
      fullPath: '/alpacas'
      preLoaderRoute: typeof AlpacasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpaca-create': {
      id: '/alpaca-create'
      path: '/alpaca-create'
      fullPath: '/alpaca-create'
      preLoaderRoute: typeof AlpacaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/myhorses/all': {
      id: '/myhorses/all'
      path: '/all'
      fullPath: '/myhorses/all'
      preLoaderRoute: typeof MyhorsesAllRouteImport
      parentRoute: typeof MyhorsesRoute
    }
    '/myhorses/$filter': {
      id: '/myhorses/$filter'
      path: '/$filter'
      fullPath: '/myhorses/$filter'
      preLoaderRoute: typeof MyhorsesFilterRouteImport
      parentRoute: typeof MyhorsesRoute
    }
    '/competition/create': {
      id: '/competition/create'
      path: '/competition/create'
      fullPath: '/competition/create'
      preLoaderRoute: typeof CompetitionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad/$adId': {
      id: '/ad/$adId'
      path: '/ad/$adId'
      fullPath: '/ad/$adId'
      preLoaderRoute: typeof AdAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$animal/$animalId': {
      id: '/$animal/$animalId'
      path: '/$animal/$animalId'
      fullPath: '/$animal/$animalId'
      preLoaderRoute: typeof AnimalAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/update': {
      id: '/quiz/$quizId/update'
      path: '/update'
      fullPath: '/quiz/$quizId/update'
      preLoaderRoute: typeof QuizQuizIdUpdateRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
    '/competition/$compId/update': {
      id: '/competition/$compId/update'
      path: '/competition/$compId/update'
      fullPath: '/competition/$compId/update'
      preLoaderRoute: typeof CompetitionCompIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition/$compId/compete': {
      id: '/competition/$compId/compete'
      path: '/competition/$compId/compete'
      fullPath: '/competition/$compId/compete'
      preLoaderRoute: typeof CompetitionCompIdCompeteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$animal/$animalId/update': {
      id: '/$animal/$animalId/update'
      path: '/update'
      fullPath: '/$animal/$animalId/update'
      preLoaderRoute: typeof AnimalAnimalIdUpdateRouteImport
      parentRoute: typeof AnimalAnimalIdRoute
    }
    '/$animal/$animalId/results': {
      id: '/$animal/$animalId/results'
      path: '/results'
      fullPath: '/$animal/$animalId/results'
      preLoaderRoute: typeof AnimalAnimalIdResultsRouteImport
      parentRoute: typeof AnimalAnimalIdRoute
    }
    '/$animal/$animalId/info': {
      id: '/$animal/$animalId/info'
      path: '/info'
      fullPath: '/$animal/$animalId/info'
      preLoaderRoute: typeof AnimalAnimalIdInfoRouteImport
      parentRoute: typeof AnimalAnimalIdRoute
    }
    '/$animal/$animalId/foals': {
      id: '/$animal/$animalId/foals'
      path: '/foals'
      fullPath: '/$animal/$animalId/foals'
      preLoaderRoute: typeof AnimalAnimalIdFoalsRouteImport
      parentRoute: typeof AnimalAnimalIdRoute
    }
    '/$animal/$animalId/delete': {
      id: '/$animal/$animalId/delete'
      path: '/delete'
      fullPath: '/$animal/$animalId/delete'
      preLoaderRoute: typeof AnimalAnimalIdDeleteRouteImport
      parentRoute: typeof AnimalAnimalIdRoute
    }
  }
}

interface MyhorsesRouteChildren {
  MyhorsesFilterRoute: typeof MyhorsesFilterRoute
  MyhorsesAllRoute: typeof MyhorsesAllRoute
}

const MyhorsesRouteChildren: MyhorsesRouteChildren = {
  MyhorsesFilterRoute: MyhorsesFilterRoute,
  MyhorsesAllRoute: MyhorsesAllRoute,
}

const MyhorsesRouteWithChildren = MyhorsesRoute._addFileChildren(
  MyhorsesRouteChildren,
)

interface QuizQuizIdRouteChildren {
  QuizQuizIdUpdateRoute: typeof QuizQuizIdUpdateRoute
}

const QuizQuizIdRouteChildren: QuizQuizIdRouteChildren = {
  QuizQuizIdUpdateRoute: QuizQuizIdUpdateRoute,
}

const QuizQuizIdRouteWithChildren = QuizQuizIdRoute._addFileChildren(
  QuizQuizIdRouteChildren,
)

interface QuizRouteChildren {
  QuizQuizIdRoute: typeof QuizQuizIdRouteWithChildren
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizQuizIdRoute: QuizQuizIdRouteWithChildren,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

interface AnimalAnimalIdRouteChildren {
  AnimalAnimalIdDeleteRoute: typeof AnimalAnimalIdDeleteRoute
  AnimalAnimalIdFoalsRoute: typeof AnimalAnimalIdFoalsRoute
  AnimalAnimalIdInfoRoute: typeof AnimalAnimalIdInfoRoute
  AnimalAnimalIdResultsRoute: typeof AnimalAnimalIdResultsRoute
  AnimalAnimalIdUpdateRoute: typeof AnimalAnimalIdUpdateRoute
}

const AnimalAnimalIdRouteChildren: AnimalAnimalIdRouteChildren = {
  AnimalAnimalIdDeleteRoute: AnimalAnimalIdDeleteRoute,
  AnimalAnimalIdFoalsRoute: AnimalAnimalIdFoalsRoute,
  AnimalAnimalIdInfoRoute: AnimalAnimalIdInfoRoute,
  AnimalAnimalIdResultsRoute: AnimalAnimalIdResultsRoute,
  AnimalAnimalIdUpdateRoute: AnimalAnimalIdUpdateRoute,
}

const AnimalAnimalIdRouteWithChildren = AnimalAnimalIdRoute._addFileChildren(
  AnimalAnimalIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlpacaCreateRoute: AlpacaCreateRoute,
  AlpacasRoute: AlpacasRoute,
  BreedRoute: BreedRoute,
  BuyhorsesRoute: BuyhorsesRoute,
  CleanstableRoute: CleanstableRoute,
  CompetitionsRoute: CompetitionsRoute,
  HorseCreateRoute: HorseCreateRoute,
  HorsesRoute: HorsesRoute,
  ImagesRoute: ImagesRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyalpacasRoute: MyalpacasRoute,
  MyhorsesRoute: MyhorsesRouteWithChildren,
  PuzzlesRoute: PuzzlesRoute,
  QuizRoute: QuizRouteWithChildren,
  QuizesRoute: QuizesRoute,
  WalletRoute: WalletRoute,
  AnimalAnimalIdRoute: AnimalAnimalIdRouteWithChildren,
  AdAdIdRoute: AdAdIdRoute,
  CompetitionCreateRoute: CompetitionCreateRoute,
  CompetitionCompIdCompeteRoute: CompetitionCompIdCompeteRoute,
  CompetitionCompIdUpdateRoute: CompetitionCompIdUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
